server:
  port: 8080

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/health?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:

    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect